### ISSUE TITLE
Outbound Requests on a USB/Network Interface

### ISSUE THREAD

**Issue by alxfu** [jerryryle/rogueportal#4]
Hi there,

much appreciating the rogueportal. one question. Would it be a good idea to have an outbound requests such as "sudo apt install x" not being redirected to 10.1.1.1 since that makes it fail. Therefore maybe the rogueportal could differentiate a bit more and only redirect everyting of the wifi interface.

short story: I gave my pi0 internet access via its USB port while rogueportal was active/installed and I connected to it via serial/GPIO. I couldnt update/install packages nor ping google.com (well that worked but I got answers from 10.1.1.1 ;) ). Could this be unintended behavior?

Much appreciated, big cheers,

Alx

**Comment by alxfu** [comment]
Dude, you are awesome! Cannot wait to try on Monday aka. tomorrow. Cheers from Germany, Alx

**Comment by jerryryle** [comment]
Good luck! Let me know if it works for you.
